name: bloc_pattern
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  cloud_firestore:
  firebase_auth:
  google_sign_in:
  flutter_bloc:
  equatable:
  meta:
  rxdart:
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

